language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Y4q3PuG7Wp3fL1FPlEMb6N30Mx5yVI2tspeHW0S54ojHeAprj0yokDzs+jfAchH5Fuwa60ac7UDygx1z98M2IuJALuguab3C8PhT4rfW/oCJ6Nb/jHL6MKUbDENwjk4C93sNTs5RyraM8g8gWE/kJI1eKlaEnCqPu89rNlemd1ywLpjvsicI3CGaobVIt9eLxqCKOk4FM8VcaMwU4pL9TSPr6B+hfh9x7BjD5pM44VdQtCiBYJJpaIyKqRzDZFfmQcvD/XAi1rOuajTD86JM/mnw2OeqVczrgdQ6ATiraub8BWyK+tNNDQzLALvFwwGdb6p+UIEWkKs9fWe3kKdrzx5FpNmkK6v4A+ULZaeF4MIORderaTuFlbIW9tHk584MWDMU89eIfTvvCxFtu2opGZKFd0TSVtpaJWLDpig7+TBIebHVGzm9ZfxxrxFPtDLlaJlrMKDaTj7gGp/HXp1ccCtqc+PmuGUIMniw2tMfbOFkqtZnkUjGY9hXa5n6lQ63aOgh1tB6mJ4J2ZQfEuUF7xtyAwOfwAciLwWl+SFQRsT9cVBBYZaISSLy2iEY1kE1K5kNLDFwv66jH+9vcuGd4d1VdAg9+ODL/k9YqScn9+mEtZ+QTe7LgbP/iPMfbHj77fcYtyfJcXMXYus+Cca6d1S3eEGXc6HfWbf/WIxF10o=
  app: sleepy-hollows-70516
  on:
    repo: lightsage88/techsite-backend
  skip_cleanup: 'true'
